package app.model.event;

public enum NotificationType {
    RENAME,
    DELETE_PROJECT,
    DELETE_DIAGRAM,
    DELETE_PACKAGE,
    DELETE_COMPONENT,
    CHANGE_AUTHOR,
    NODE_SELECTION_CHANGED,
    PACKAGE_SELECTED,
    PATH_CHANGED,
    PAINTER_ADDED,
    PAINTER_REMOVED,
    EXISTING_TAB_OPENED,
    PAINTER_STATE_CHANGED,
    PAINTER_POSITION_CHANGED
}
