package message;

public enum PossibleErr {
    NODE_CANNOT_BE_DELETED,
    NAME_CANNOT_BE_EMPTY,
    PROJECT_MUST_BE_SELECTED_TO_CREATE_A_PACKAGE,
    PACKAGE_MUST_BE_SELECTED_TO_CREATE_A_COMPONENT,
    NAME_CANNOT_BE_CHANGED,
    UNABLE_TO_ADD_PROJECT,
    UNABLE_TO_ADD_PACKAGE,
    UNABLE_TO_ADD_COMPONENT,
    PROJECT_CANNOT_BE_DELETED,
    PROJECT_EXPLORER_MUST_BE_SELECTED_TO_CREATE_A_PROJECT,
    CANNOT_DELETE_ELEMENT,
    ONLY_USE_DOUBLE_CLICK_ON_NODES
}
