package app.model.message;

public enum PossibleErr {
    NODE_CANNOT_BE_DELETED,
    NAME_CANNOT_BE_EMPTY,
    PROJECT_OR_PACKAGE_MUST_BE_SELECTED_TO_CREATE_A_PACKAGE,
    PACKAGE_MUST_BE_SELECTED_TO_CREATE_A_DIAGRAM,
    DIAGRAM_MUST_BE_SELECTED_TO_CREATE_A_COMPONENT,
    NAME_CANNOT_BE_CHANGED,
    UNABLE_TO_ADD_PROJECT,
    UNABLE_TO_ADD_PACKAGE,
    UNABLE_TO_ADD_COMPONENT,
    PROJECT_CANNOT_BE_DELETED,
    PROJECT_EXPLORER_MUST_BE_SELECTED_TO_CREATE_A_PROJECT,
    CANNOT_DELETE_ELEMENT,
    ONLY_USE_DOUBLE_CLICK_ON_NODES,
    NEED_TO_SELECT_PROJECT_TO_ADD_AUTHOR,
    NEED_TO_SELECT_PROJECT_TO_ADD_PATH,
    CANNOT_DELETE_PROJECT_EXPLORER,
    PROJECT_MUST_BE_SELECTED_FOR_THIS_ACTION,
    DIAGRAM_MUST_BE_SELECTED_FOR_THIS_ACTION,
    SUCCESSFULLY_SAVED_PROJECT,
    SUCCESSFULLY_SAVED_TEMPLATE,
    SUCCESSFULLY_GENERATED_CODE,
    NO_DIAGRAMS_EDITED
}
